// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJwj9XkhhWbU0o5EZoy4zCFA-8GN-Kog',
    appId: '1:1030081155379:web:140186ce4f22670e766e46',
    messagingSenderId: '1030081155379',
    projectId: 'pot-hid-d0d65',
    authDomain: 'pot-hid-d0d65.firebaseapp.com',
    storageBucket: 'pot-hid-d0d65.appspot.com',
    measurementId: 'G-86FEP2QV9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GWxk51LskRdyOBaS7Q7TEqvK82AEITw',
    appId: '1:1030081155379:android:6f7ee23f3390d356766e46',
    messagingSenderId: '1030081155379',
    projectId: 'pot-hid-d0d65',
    storageBucket: 'pot-hid-d0d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusQeWws6g5KV4NI1GbXxDWeMdlcyP-aA',
    appId: '1:1030081155379:ios:d1747f6d3f0ec597766e46',
    messagingSenderId: '1030081155379',
    projectId: 'pot-hid-d0d65',
    storageBucket: 'pot-hid-d0d65.appspot.com',
    iosClientId: '1030081155379-hn300lr982tuaumupc0k1oa3av5ud22c.apps.googleusercontent.com',
    iosBundleId: 'com.example.potHid',
  );
}
